--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DuoIncure/ComplexRelics
build-by-default: true
branches:
- pm5
projects:
  ComplexRelics:
    path: ""
    lint:
      phpstan: false
...
