---
name: Relics
version: 3.0.0
main: DuoIncure\Relics\Main
api: 5.0.0
src-namespace-prefix: DuoIncure\Relics
description: An awesome relic plugin for PocketMine-MP!
permissions:
  relics.command.giverelic:
    default: op
    description: Give relics to a player
  relics.command.relicall:
    default: op
    description: Give relics to all online players
...
